#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

Rscript Figure_1/Figure_1C.R
Rscript Figure_1/Figure_1D.R
Rscript Figure_1/Figure_1E_1F_1G.R
Rscript Figure_2/Figure_2B_2C_2D.R
Rscript Figure_3/Figure_3.R
Rscript Figure_4/Figure_4E_4F_4G.R