#########################################
# Figure 1D plot
# This script makes NCC and SCLC cfDNA
# PCA concordance plot
#
# Written by Sami Ul Haq (Dec 2021)

# The PCA was generated by examining 300bp ENCODE-blacklisted filtered, whole-genome methylation profiles between non-cancer controls (NCCs) and SCLC cfDNA using DESeq2 on an HPC node with 180GB memory. The plotPCA() function in DESeq2 was used to generate the PCA and save the PCA data
# See Zenodo link for downloading data:
# Ul Haq, Sami, Tsao, Ming S., Cabanero, Michael, de Carvalho, Daniel, Liu, Geoffrey, Bratman, Scott V., & Lok, Benjamin H. (2022). Processed counts data of cfMeDIP-seq profiles of small cell lung cancer patients [Data set]. In Cell Press iScience (Vol. 25, Number 12). Zenodo. https://doi.org/10.5281/zenodo.7235989

library(ggplot2)

named.color <- c("Non-cancer donor cfDNA"="#4daf4a", "SCLC cfDNA"="#e41a1c")

load("../data/PCA.data.NCC.vs.SCLC.cfDNA.RData")
levels(pca.data$condition) <- c("Non-cancer donor cfDNA", "SCLC cfDNA")

ggplot(pca.data, aes(PC1, PC2, color=condition, shape=condition)) +
  geom_point(size=6) +
  theme_bw() +
  theme(axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size=18)) + 
  xlab("PC1: 60% variance") +
  ylab("PC2: 8% variance") +
  scale_color_manual(values=named.color)

# pdf version
ggsave(file=paste0("../results/Figure_1D.pdf"), width=14, height=7, units="in")