#########################################
# Figure 1C plot
# This script makes paired CDX tumour tissue
# PCA concordance plot
#
# Written by Sami Ul Haq (Dec 2021)

# The PCA was generated by examining 300bp ENCODE-blacklisted filtered, whole-genome methylation profiles between CDX and paired patient cfDNA using DESeq2 on an HPC node with 60GB memory. The plotPCA() function in DESeq2 was used to generate the PCA and save the PCA data
# See Zenodo link for downloading data:
# Ul Haq, Sami, Tsao, Ming S., Cabanero, Michael, de Carvalho, Daniel, Liu, Geoffrey, Bratman, Scott V., & Lok, Benjamin H. (2022). Processed counts data of cfMeDIP-seq profiles of small cell lung cancer patients [Data set]. In Cell Press iScience (Vol. 25, Number 12). Zenodo. https://doi.org/10.5281/zenodo.7235989

library(ggplot2)

# For baseline models
load("../data/PCA.data.CDX.vs.SCLC.cfDNA.RData")

label.names <- substr(pca.data$name, 1, 9)

# BASELINE ONLY
PC1.variance <- "28% variance"
PC2.variance <- "20% variance"

# for baseline models
pca.data$patient <- pca.data$name
pca.data$patient <- substr(pca.data$patient, 1, 7)
pca.data$patient[1:7] <- c("SCLC.071",
                           "SCLC.074",
                           "SCLC.049",
                           "SCLC.050",
                           "SCLC.058",
                           "SCLC.062",
                           "SCLC.073")

named.color <- c("SCLC.071" = "#b2df8a",
                 "SCLC.074" = "#33a02c",
                 "SCLC.049" = "#e31a1c",
                 "SCLC.050" = "#fdbf6f",
                 "SCLC.058" = "#ff7f00",
                 "SCLC.062" = "#e8da87",
                 "SCLC.073" = "#b15928")

ggplot(pca.data, aes(x=PC1, y=PC2, shape=condition, color=patient)) +
  geom_point(size=6) +
  theme_bw() +
  theme(axis.text.x = element_text(size=18),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size=18)) +
  xlab(paste("PC1", PC1.variance)) +
  ylab(paste("PC2", PC2.variance)) +
  labs(shape="Sample type") +
  scale_color_manual(values=named.color)


# pdf saved
ggsave(filename = "../results/Figure_1C.pdf", units="in", width=10, height=5)
